INSERT INTO `items` VALUES ('Meat', 'Meat', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Gamey_Meat', 'Gamey Meat', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Small_Leather', 'Small Leather', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Big_Leather', 'Big Leather', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Feather', 'Feather', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Snake_Poison', 'Snake Poison', '10', '1', 'item_standard', '1');

INSERT INTO `items` VALUES ('Duck_Egg', 'Duck Egg', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Gator_Egg_3', 'Aligator Egg 3', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Gator_Egg_4', 'Aligator Egg 4', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Gator_Egg_5', 'Aligator Egg 5', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Goose_Egg_4', 'Goose Egg', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Volture_Egg', 'Volture Egg', '10', '1', 'item_standard', '1');

INSERT INTO `items` VALUES ('Agarita', 'Agarita', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Alaskan_Ginseng', 'Alaskan Ginseng', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('American_Ginseng', 'American Ginseng', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Bay_Bolete', 'Bay Bolete', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Bitter_Weed', 'Bitter Weed', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Black_Berry', 'Black Berry', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Black_Currant', 'Black Currant', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Blood_Flower', 'Blood Flower', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Burdock_Root', 'Burdock Root', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Cardinal_Flower', 'Cardinal Flower', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Chanterelles', 'Chanterelles', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Choc_Daisy', 'Choc Daisy', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Bulrush', 'Bulrush', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Creekplum', 'Creekplum', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Creeking_Thyme', 'Creeking Thyme', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Crows_Garlic', 'Crows Garlic', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Desert_Sage', 'Desert Sage', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('English_Mace', 'English Mace', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Evergreen_Huckleberry', 'Evergreen Huckleberry', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Golden_Currant', 'Golden Currant', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Hummingbird_Sage', 'Hummingbird Sage', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Indian_Tobbaco', 'Indian Tobbaco', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Milk_Weed', 'Milk Weed', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Oleander_Sage', 'Oleander Sage', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Oregano', 'Oregano', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Parasol_Mushroom', 'Parasol Mushroom', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Prairie_Poppy', 'Prairie Poppy', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Rams_Head', 'Rams Head', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Red_Raspberry', 'Red Raspberry', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Red_Sage', 'Red Sage', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Saltbush', 'Saltbush', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Texas_Bonnet', 'Texas Bonnet', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Violet_Snowdrop', 'Violet Snowdrop', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Wild_Carrot', 'Wild Carrot', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Wild_Feverfew', 'Wild Feverfew', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Wild_Mint', 'Wild Mint', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Wild_Rhubarb', 'Wild Rhubarb', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Wintergreen_Berry', 'Wintergreen Berry', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Wisteria', 'Wisteria', '10', '1', 'item_standard', '1');
INSERT INTO `items` VALUES ('Yarrow', 'Yarrowd', '10', '1', 'item_standard', '1');

