Config.Language = {
    ["presstobuy"] = "Personnaliser les armes",
    ["presstocraft"] = "Artisanat d'armes",
    ["presstoshop"] = "armurerie",
    ["tooclose"] = "Quelqu'un est trop proche",
    ["openmenu"] = "Ouvrir",
    ["rotateitem1"] = "Appuyez sur ~e~1~q~ pour faire pivoter l'arme",
    ["rotateitem2"] = "Appuyez sur ~e~2~q~ pour faire pivoter l'arme",
    ["rotateitem3"] = "Appuyez sur ~e~3~q~ pour faire pivoter l'arme",
    ["rotateitem4"] = "Appuyez sur ~e~4~q~ pour faire pivoter l'arme",

    ["dollar"] = "$",



    ["craftingloading"] = "Artisanat...",
    ["customloading"] = "Monter les personnalisations..",
    ["Pleaserequip"] = "Veuillez équiper votre arme de l'inventaire",
    ["scrolltoexit"] = "Faites défiler vers le bas pour quitter le menu",
    ["wrongjobcuztom"] = "Vous n'avez pas le poste/rang requis pour effectuer les ajustements",
    ["wrongjobcrafting"] = "Vous n'avez pas le job/rang requis pour fabriquer des armes",
    ["customization"] = "Personnaliser les armes",
    ["crafting"] = "fabrication",
    ["shop"] = "magasin d'armes",
    ["buyweapons"] = "Acheter des armes",
    ["buyammo"] = "acheter des munitions",
    ["weaponcrafting"] = "fabrication d'armes",
    ["ammocrafting"] = "fabrication de munitions",
    ["areusureexit"] = "Êtes-vous sûr d'avoir terminé ?",
    ["comps"] = "Composants d'armes",
    ["sights"] = "viseurs d'armes",
    ["rifling"] = "Arme Fusil",
    ["other"] = "Canon d'arme",
    ["scopecolor"] = "ScopeMaterial",
    ["wrap"] = "Emballage d'arme",
    ["wrapcolor"] = "WrapColor",
    ["barrel"] = "matériau du baril",
    ["trigger"] = "matériel de déclenchement",
    ["variant"] = "Variante d'arme",
    ["frame"] = "Matériau du cadre",
    ["frontsight"] = "Matériau du guidon",
    ["cylinder"] = "Matériau du mécanisme",
    ["gripbody"] = "matériau de la poignée",
    ["grip"] = "Autocollant de prise en main",
    ["decal"] = "Autocollants d'armes",
    ["decalcylinder"] = "Décalques de mécanisme",
    ["decalframe"] = "Décalcomanies de cadre",
    ["decalbarrel"] = "Autocollants de canon",
    ["decalcolor"] = "Matériau de l'autocollant",
    ["cylinder2"] = "Matériau des décalcomanies du mécanisme",
    ["frame2"] = "Matériau des décalcomanies du cadre",
    ["barrel2"] = "Matériau des décalcomanies du baril",
    ["buyselect"] = "Acheter sélectionner",
    ["totale"] = "Totale : ",
    ["exitmenu"] = "Quitter le menu",
    ["cost"] = "Coût : ",
    ["craft"] = "Artisanat",
    ["count"] = "Compter : ",
    ["yes"] = "Oui",
    ["no"] = "Non",
    ["remove"] = "Supprimer",
    ["price"] = " / Prix : ",
    ["label"] = "Libellé : ",
    ["wrongwptype"] = "Mauvais type d'arme",
    ["craftingwepmods"] = "Crafting Weapon Mods",
    ["cantafford"] = "Je ne peux pas me le permettre",
    ["syn_weapons"] = "Armes : ",
    ["acheté"] = " Acheté ",
    ["youbuyta"] = "Vous achetez",
    ["fors"] = " pour ",
    ["nomoney"] = "Vous n'avez pas assez d'argent",
    ["cantcarrywep"] = "Vous ne pouvez pas porter plus d'armes",
    ["cantcarryitem"] = "Vous ne pouvez plus en transporter",
    ["crafted"] = " Fabriqué ",
    ["nomaterial"] = "Pas assez de matériaux",
    ["weprec"] = "Vous avez reçu une arme",




    -----nouvelles lignes
    ["confirm"] = "Confirmer",
    ["amount"] = "montant",
    ["invalidamount"] = "Montant invalide",
}
