 REPLACE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `id`, `metadata`, `desc`) VALUES
 ('Agarita', 'Agarita', '10', '1', 'item_standard',  1, 19058, '{}', ' '),
 ('Alaskan_Ginseng', 'Ginseng d Alaska', '10', '1', 'item_standard',  1, 19059, '{}', ' '),
 ('American_Ginseng', 'Ginsend Americain', '10', '1', 'item_standard',  1, 19060, '{}', ' '),
 ('Bay_Bolete', 'Bolet', '10', '1', 'item_standard',  1, 19061, '{}', ' '),
 ('Bitter_Weed', 'Plante amère', '10', '1', 'item_standard',  1, 19062, '{}', ' '),
 ('Black_Berry', 'Mûre sauvage', '10', '1', 'item_standard',  1, 19063, '{}', ' '),
 ('Black_Currant', 'Cassis', '10', '1', 'item_standard',  1, 19064, '{}', ' '),
 ('Blood_Flower', 'Asclépiade à fleurs rouges', '10', '1', 'item_standard',  1, 19065, '{}', ' '),
 ('Burdock_Root', 'Racine de bardane', '10', '1', 'item_standard',  1, 19066, '{}', ' '),
 ('Cardinal_Flower', 'Lobélie du cardinal', '10', '1', 'item_standard',  1, 19067, '{}', ' '),
 ('Chanterelles', 'Chanterelles', '10', '1', 'item_standard',  1, 19068, '{}', ' '),
 ('Choc_Daisy', 'Herbe à Serpent', '10', '1', 'item_standard',  1, 19069, '{}', ' '),
 ('Bulrush', 'Jonc des chaisiers', '10', '1', 'item_standard',  1, 19070, '{}', ' '),
 ('Creekplum', 'Creekplum', '10', '1', 'item_standard',  1, 19071, '{}', ' '),
 ('Creeking_Thyme', 'Thym sauvage', '10', '1', 'item_standard',  1, 19072, '{}', ' '),
 ('Crows_Garlic', 'ciboulette', '10', '1', 'item_standard',  1, 19073, '{}', ' '),
 ('Desert_Sage', 'Sauge du désert', '10', '1', 'item_standard',  1, 19074, '{}', ' '),
 ('English_Mace', 'Noix de muscade', '10', '1', 'item_standard',  1, 19075, '{}', ' '),
 ('Evergreen_Huckleberry', 'Airelle à feuilles persistantes', '10', '1', 'item_standard',  1, 19076, '{}', ' '),
 ('Golden_Currant', 'Groseillier doré', '10', '1', 'item_standard',  1, 19077, '{}', ' '),
 ('Hummingbird_Sage', 'Sauge pour colibris', '10', '1', 'item_standard',  1, 19078, '{}', ' '),
 ('Indian_Tobbaco', 'Tabac indien', '10', '1', 'item_standard',  1, 19079, '{}', ' '),
 ('Milk_Weed', 'Asclépiade', '10', '1', 'item_standard',  1, 19080, '{}', ' '),
 ('Oleander_Sage', 'Sauge Écarlate', '10', '1', 'item_standard',  1, 19081, '{}', ' '),
 ('Oregano', 'Origan', '10', '1', 'item_standard',  1, 19082, '{}', ' '),
 ('Parasol_Mushroom', 'Coulemelle', '10', '1', 'item_standard',  1, 19083, '{}', ' '),
 ('Prairie_Poppy', 'Coquelicot des prairies', '10', '1', 'item_standard',  1, 19084, '{}', ' '),
 ('Rams_Head', 'Poules Des bois', '10', '1', 'item_standard',  1, 19085, '{}', ' '),
 ('Red_Raspberry', 'Framboisier rouge', '10', '1', 'item_standard',  1, 19086, '{}', ' '),
 ('Red_Sage', 'Sauge Rouge', '10', '1', 'item_standard',  1, 19087, '{}', ' '),
 ('Saltbush', 'Arroche Salée', '10', '1', 'item_standard',  1, 19088, '{}', ' '),
 ('Texas_Bonnet', 'Couronne de Texas', '10', '1', 'item_standard',  1, 19089, '{}', ' '),
 ('Violet_Snowdrop', 'Perce-neige violet', '10', '1', 'item_standard',  1, 19090, '{}', ' '),
 ('Wild_Carrot', 'Framboisier rouge', '10', '1', 'item_standard',  1, 19091, '{}', ' '),
 ('Wild_Feverfew', 'Camomille matricaire', '10', '1', 'item_standard',  1, 19092, '{}', ' '),
 ('Wild_Mint', 'Menthe sauvage', '10', '1', 'item_standard',  1, 19093, '{}', ' '),
 ('Wild_Rhubarb', 'Rhubarbe sauvage', '10', '1', 'item_standard',  1, 19094, '{}', ' '),
 ('Wintergreen_Berry', 'Gaulthérie couchée', '10', '1', 'item_standard',  1, 19095, '{}', ' '),
 ('Wisteria', 'Glycine', '10', '1', 'item_standard',  1, 19096, '{}', ' '),
 ('Yarrow', 'Yarrowd', '10', '1', 'item_standard',  1, 19097, '{}', ' ');