Lang = {}

Lang.accessories = 'Accessoires'
Lang.allCategories = 'Toutes catégories'
Lang.armor = 'Armure'
Lang.badges = 'Insignes'
Lang.belt_buckles = 'Boucles de ceinture'
Lang.belts = 'Ceintures'
Lang.bigTitle = 'Tailleur'
Lang.boot_accessories = 'Accessoires de bottes'
Lang.boots = 'Bottes'
Lang.buyClothes = 'Acheter des vêtements'
Lang.buyClothesDescription = 'Acheter de nouveaux vêtements'
Lang.chaps = 'Chaps'
Lang.cloaks = 'Capes'
Lang.coats = 'Manteaux'
Lang.coats_closed = 'Manteaux fermés'
Lang.devise = '$'
Lang.dresses = 'Robes'
Lang.enterName = 'Entrez le nom'
Lang.eyewear = 'Lunettes'
Lang.free = 'Gratuit'
Lang.gauntlets = 'Gantelets'
Lang.gloves = 'Gants'
Lang.gunbelt_accs = 'Accessoires de ceinture'
Lang.gunbelts = 'Ceintures'
Lang.hats = 'Chapeaux'
Lang.holsters_left = 'Étuis à gauche'
Lang.jewelry_bracelets = 'Bijoux Bracelets'
Lang.jewelry_rings_left = 'Bague gauche'
Lang.jewelry_rings_right = 'Bague droite'
Lang.loadouts = 'Sac épaule'
Lang.masks = 'Masque'
Lang.myClothes = 'Items acheter'
Lang.myClothesDescription = 'Tous les articles que vous avez déjà achetés'
Lang.of = '%1 de %2'
Lang.neckties = 'Cravates'
Lang.neckwear = 'Foulards'
Lang.new = 'Nouveau'
Lang.number = 'Nombre %1'
Lang.outfit = 'Tenue'
Lang.outfitDescription = 'Gérez vos tenues'
Lang.outfitSaveCurrent = 'Enregistrez votre tenue actuelle'
Lang.pants = 'Pantalon'
Lang.ponchos = 'Ponchos'
Lang.price = 'Prix'
Lang.satchels = 'Cartables'
Lang.shirts_full = 'Chemises'
Lang.skirts = "Jupes"
Lang.spats = 'Guêtres'
Lang.suspenders = 'Bretelles'
Lang.variation = 'Variation'
Lang.vests = 'Gilets'
Lang.remove = 'Retirer'

--Prompt
Lang.back = "Retour"
Lang.buy = "Acheter"
Lang.delete = "Supprimer"
Lang.enter = "Ouvrir le magasin"
Lang.enterWardrobe = "Ouvrir l armoire"
Lang.exit = "Quitter"
Lang.resell = "Revendre: $%.2f"
Lang.select = "Selectionner"
Lang.use = "Utiliser"
Lang.turn = "Tourner"

Lang.NoMoney = "Vous n avez pas assez d'argent"

--Blips
Lang.blipStoreName = "Magasin de vêtement"
Lang.blipWardrobe = "Armoire"
