Lang = {}

Lang.accessories = 'Accessories'
Lang.allCategories = 'All Categories'
Lang.armor = 'Armor'
Lang.badges = 'Badges'
Lang.belt_buckles = 'Gunbelt Buckles'
Lang.belts = 'Belts'
Lang.bigTitle = 'Tailor'
Lang.bigTitleWardrobe = 'Wardrobe'
Lang.boot_accessories = 'Boot accessories'
Lang.boots = 'Boots'
Lang.buyClothes = 'Buy Clothes'
Lang.buyClothesDescription = 'Buy new Clothes'
Lang.chaps = 'Chaps'
Lang.cloaks = 'Cloaks'
Lang.coats = 'Coats'
Lang.coats_closed = 'Coats closed'
Lang.devise = '$'
Lang.dresses = 'Dresses'
Lang.enterName = 'Enter the name'
Lang.eyewear = 'Eyewear'
Lang.free = 'Free'
Lang.gauntlets = 'Gauntlets'
Lang.gloves = 'Gloves'
Lang.gunbelt_accs = 'Gunbelt Accessories'
Lang.gunbelts = 'Gunbelts'
Lang.hats = 'Hats'
Lang.holsters_left = 'Holsters left'
Lang.jewelry_bracelets = 'Jewelry Bracelets'
Lang.jewelry_rings_left = 'Rings left'
Lang.jewelry_rings_right = 'Rings right'
Lang.loadouts = 'Loadouts'
Lang.masks = 'Masks'
Lang.myClothes = 'Items bought'
Lang.myClothesDescription = "All items you already bought"
Lang.of = '%1 of %2'
Lang.neckties = 'Neckties'
Lang.neckwear = 'Neckwear'
Lang.new = 'New'
Lang.number = 'Number %1'
Lang.outfit = 'Outfit'
Lang.outfitDescription = 'Manage your outfits'
Lang.outfitSaveCurrent = 'Save your current outfit'
Lang.pants = 'Pants'
Lang.ponchos = 'Ponchos'
Lang.price = 'Price'
Lang.satchels = 'Satchels'
Lang.shirts_full = 'Shirts'
Lang.skirts = "Skirts"
Lang.spats = 'Spats'
Lang.suspenders = 'Suspenders'
Lang.variation = 'Variation'
Lang.vests = 'Vests'
Lang.remove = 'Remove'

--Prompt
Lang.back = "Back"
Lang.buy = "Buy"
Lang.buyGold = "Buy with gold"
Lang.cantSell = "You can't resell piece that is used in outfit: \"%s\""
Lang.delete = "Delete"
Lang.enter = "Open book"
Lang.enterWardrobe = "Open wardrobe"
Lang.exit = "Exit"
Lang.resell = "Resell: $%.2f"
Lang.select = "Select"
Lang.use = "Use"
Lang.turn = "Turn"
Lang.openStore = "Open store"

Lang.NoMoney = "Not enough money"

--Blips
Lang.blipStoreName = "Clothing store"
Lang.blipWardrobe = "Wardrobe"
