Config = {

-- ##### SELECT YOUR FRAMEWORK #####
-- IMPORTANT: ONLY ONE MUST BE TRUE, OTHERS SHOULD BE FALSE.
["VORP"] = true,
["RedEM"] = false,
-- #################################

-- INVENTORY SETTINGS
["CloseOnUse"] = false, -- Determines whether the inventory will close after using an item. VORP must be true!	

-- NOTIFICATIONS
["MSG"] = "You consumed ", -- Message to display when consumed 
["FoodNotify"] = "You hear your belly rumbling and start to feel weak...", -- When your food is low it displays this notification
["WaterNotify"] = "Your throat feels incredibly dry and your lips begin to dry out...", -- When your water is low it displays this notification
["FoodNotification"] = 20, -- Determines when the ["LowFoodNotification"] notifications displays
["WaterNotification"] = 20, -- Determines when the ["LowWaterNotification"] notifications displays

-- INITIAL VALUES
["InitialFood"] = 100, -- INITIAL FOOD -- MAX VALUE 100%
["InitialWater"] = 100, -- INITIAL FOOD -- MAX VALUE 100%

-- METABOLISM
-- **IMPORTANT: REMEMBER FEMALE PLAYERS MAY NOT UPDATE ITS BODY**
["MetabolismFiesta"] = false, -- This will disable visual body changes

["InitialMetabolism"] = 10000, -- Initial metabolism where 0 is super skinny and 20000 is super fat, 10000 would be normal
["MetabolismLossIdle"] = 0.4, -- Metabolism drop rate while on stand by
["MetabolismLossWalking"] = 0.5, -- Metabolism drop rate per tick while walking
["MetabolismLossRunning"] = 1, -- Metabolism drop rate per tick while running. Go do some exercise!

-- TICK: This is the time (rate) it takes to excecute every check 
-- For e.g: 2 food is drain per tick
-- 1000 = 1 second; 20000 = 20 seconds; 3600 = 3,5 seconds
-- **WARNING: ONLY TOUCH THIS VARIABLES IF YOU NEED, MAY HIGHLY AFFECT OPERATION**
["NeedsTick"] = 60000, -- Checks your needs over time
["MetabolismTick"] = 60000, -- Checks your metabolism over time

-- DRAINS PER TICK ("NeedsTick")
["FoodDrainIdle"] = 0.1, -- Food drop rate on stand by
["FoodDrainRunning"] = 0.6, -- Food drop rate while running
["FoodDrainWalking"] = 0.4, -- Food drop rate while walking
["WaterDrainIdle"] = 0.1, -- Water drop rate on stand by
["WaterDrainRunning"] = 0.6, -- Water drop rate while running
["WaterDrainWalking"] = 0.4, -- Water drop rate while walking

-- HEALTH LOSS STRIPE
["HealthLoss"] = 0.2, -- Health you lose per tick
["FoodStripe"] = 0, -- Food stripe that determines when you start to lose health
["WaterStripe"] = 0, -- Water stripe that determines when you start to lose health

-- TEMPERATURE DEBUFF STRIPE
["TooCold!"] = true, -- Enables/disables Temperature System
["MinTemperature"] = -5, -- -20°C From this temperature below, you'll lose more food and water
["MaxTemperature"] = 38, -- 20°C From this temperature above, you'll lose more food and water
["TempNotify1"] = "You are feeling very cold, you should cover yourself more!!",
["TempNotify2"] = "You're cold, you should cover yourself",
["TempNotify3"] = "You're freezing cover yourself up, otherwise you will die!",

-- FOOD AND WATER DROP RATE FROM TEMPERATURE
["WaterHotLoss"] = 0, -- Water drop rate increment for higher temperatures
["FoodColdLoss"] = 0, -- Food drop rate increment for lower temperatures

-- DRUNK SYSTEM
["VomitMe"] = true, -- Enables/disables Vomit system
["DisableDrunkRun"] = true, -- Enables/disables running when drunk

-- Drink Cup Animation Settings
["DrinkCupAnim"] = 60000, -- Determines how long the user will hold the coffee before throwing it away
	
-- CLOTHES TEMPERATURE
-- Temperature increment each clothes gives.
["HatTemp"] = 1, -- Hats
["ShirtTemp"] = 2, -- Shirts
["PantsTemp"] = 2, -- Pants
["BootsTemp"] = 2, -- Boots
["CoatTemp"] = 3, -- Coats
["ClosedCoatTemp"] = 4, -- Closed Coats
["GlovesTemp"] = 1, -- Gloves
["VestTemp"] = 1, -- Vest
["PonchoTemp"] = 5, -- Poncho

}

--
-- ANIMATION LIST
-- Thanks to @Chico for helping me get all this cool animations.
--
-- 'eat' = You will make a simple eat animation with any prop you select to it ("PropName" variable)
-- 'drink' = You will make a simple drink animation with any prop you select to it ("PropName" variable)
-- 'drink_cup' = Drink from a coffee cup
-- 'smoke' = Smoke a cigar
-- 'bowl' = Animation where you eat from a bowl
-- 'shortbottle' = Animation where you drink from a short bottle
-- 'longbottle' = Animation where you drink from a long bottle
-- 'syringe' = Animation to inject yourself with a syringe
-- 'berry' = Animation where you eat berries


-- SOME PROPS
--
-- p_bottlejd01x = Whyskey bottle
-- p_bottlebeer01a = Beer bottle
-- p_bottlewine01x = Wine bottle
-- You can find more props in http://rdr2.mooshe.tv/


-- SOME EFFECTS
-- PlayerDrunk01
-- PlayerDrunkAberdeen
-- PlayerDrugsPoisonWell
-- You can find more effects in https://github.com/femga/rdr3_discoveries/blob/master/graphics/animpostfx/animpostfx.lua


-- JUST ADD YOUR ITEMS HERE WITH THE VALUES YOU WANT
-- CHECK YOUR COMMAS AND TYPING!!!
-- MAKE SURE YOU CHANGE THE DEFAULT VALUES. THE ONES DISPLAYED HERE ARE TEST VALUES!
Config.ItemsToUse = {

	{
		["Name"] = "consumable_kidneybeans_can",
		["DisplayName"] = "Canned Beans",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "conserve_de_legumes",
		["DisplayName"] = "Conserve de legumes",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 165,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "conserve_de_viande",
		["DisplayName"] = "Conserve de viande",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 165,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "viande_cuite",
		["DisplayName"] = "Viande cuite",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 65,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
        ["Name"] = "water", 
        ["DisplayName"] = "Bouteille d eau", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,
    },
    {
        ["Name"] = "consumable_raspberrywater", 
        ["DisplayName"] = "Jus de baies", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,
    },
    {
        ["Name"] = "boisson_fruits", 
        ["DisplayName"] = "Boisson aux fruits", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,
    },
    {
        ["Name"] = "can100", 
        ["DisplayName"] = "Boisson aux fruits", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,
    },
    {
        ["Name"] = "can75", 
        ["DisplayName"] = "Boisson aux fruits", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,

    },
    {
        ["Name"] = "can50", 
        ["DisplayName"] = "Boisson aux fruits", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,
    },
    {
        ["Name"] = "can25", 
        ["DisplayName"] = "Boisson aux fruits", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,
    },
    {
        ["Name"] = "consumable_coffee", 
        ["DisplayName"] = "Coffee", 
        ["Animation"] = "drink_cup",
        ["PropName"] = "p_mugcoffee01x",
		["Remove"] = true,
        ["Metabolism"] = -5000,
        ["Hunger"] = 0,
        ["Thirst"] = 35,
        ["InnerCoreStamina"] = 50,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 100.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = false,
        ["DrinkCount"] = 0,
        ["Effect"] = "",
        ["EffectDuration"] = 0,
    },
    {
        ["Name"] = "bottledbeer", 
        ["DisplayName"] = "Beer", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
    {
        ["Name"] = "whiskey", 
        ["DisplayName"] = "Whiskey", 
        ["Animation"] = "longbottle",
        ["PropName"] = "p_bottlejd01x",
		["Remove"] = true,
        ["Metabolism"] = 225,
        ["Hunger"] = 0,
        ["Thirst"] = 10,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 2,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 120000,
    },



    --
    --
    --
    --
    --
    --
    --
    --
    
    
    {
		["Name"] = "v_sanglier_g",
		["DisplayName"] = "Sanglier grillé a l origan",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

    {
		["Name"] = "viande_filandreuse",
		["DisplayName"] = "Viande filandreuse",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

    {
		["Name"] = "viande_grenouille",
		["DisplayName"] = "Cuisse De Grenouille",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

    {
		["Name"] = "viande_venaison",
		["DisplayName"] = "Viande venaison",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "viande_serpent",
		["DisplayName"] = "Viande de serpent",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "viande_sang_froid",
		["DisplayName"] = "Viande sang froid",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

    {
		["Name"] = "viande_grosgibier",
		["DisplayName"] = "Viande gros gibier",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

    {
		["Name"] = "viande_gigot",
		["DisplayName"] = "Viande gigot",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "viande_sanglier",
		["DisplayName"] = "Viande sanglier",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},    
    {
		["Name"] = "viande_cerf",
		["DisplayName"] = "Viande cerf",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    
    {
		["Name"] = "viande_exotic",
		["DisplayName"] = "Viande exotic",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "viande_volaille",
		["DisplayName"] = "Viande volaille",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
    {
		["Name"] = "viande_gibierplume",
		["DisplayName"] = "Viande gibier plume",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

	{
		["Name"] = "b_harricot",
		["DisplayName"] = "Boite d'harricot",
		["Animation"] = "eat",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

	{
		["Name"] = "c_iguane",
		["DisplayName"] = "Chillis d'iguane",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},


	{
		["Name"] = "bouillon1",
		["DisplayName"] = "bouillon de legumes",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},

	{
		["Name"] = "bouillon2",
		["DisplayName"] = "Saumon fumée accompagnée de pommes de terre",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},


	--
	--
	--
	--
	--
	--
	--
	--
	---
	{
		["Name"] = "viande_filandreuse",
		["DisplayName"] = "Viande filandreuse",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_grenouille",
		["DisplayName"] = "Viande de Grenouille",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
		{
		["Name"] = "viande_venaison",
		["DisplayName"] = "Viande de venaison",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_serpent",
		["DisplayName"] = "Viande de serpent",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_sang_froid",
		["DisplayName"] = "Viande à sang froid",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_grosgibier",
		["DisplayName"] = "Viande gros gibier",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_gigot",
		["DisplayName"] = "Viande de Gigot",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_sanglier",
		["DisplayName"] = "Viande de Sanglier",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_cerf",
		["DisplayName"] = "Viande de Cerf",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_exotic",
		["DisplayName"] = "Viande d'annimal exotic",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_volaille",
		["DisplayName"] = "Viande de canard",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "viande_gibierplume",
		["DisplayName"] = "Viande de Gibier à plumes",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "bouillon1",
		["DisplayName"] = "Bouillon",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},
	{
		["Name"] = "bouillon2",
		["DisplayName"] = "Saumon a la patate",
		["Animation"] = "bowl",
		["PropName"] = "s_canbeans01x",
		["Remove"] = true,
		["Metabolism"] = 850,
		["Hunger"] = 650,
		["Thirst"] = 0,
		["InnerCoreStamina"] = 10,
		["InnerCoreStaminaGold"] = 0.0,
		["OuterCoreStaminaGold"] = 0.0,
		["InnerCoreHealth"] = 10,
		--["OuterCoreHealth"] = ,
		["InnerCoreHealthGold"] = 0.0,
		["OuterCoreHealthGold"] = 0.0,
		
		-- HardAlcohol, Soft Alcohol and DrinkCount are only used in "shortbottle" and "longbottle" animations
		["HardAlcohol"] = false,
		["SoftAlcohol"] = false,
		["DrinkCount"] = 0,
		["Effect"] = "",
		["EffectDuration"] = 0,
	},










	{
        ["Name"] = "vin", 
        ["DisplayName"] = "vin", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },	
	{
        ["Name"] = "whisky", 
        ["DisplayName"] = "whisky", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
	{
        ["Name"] = "biere", 
        ["DisplayName"] = "Biere", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
	{
        ["Name"] = "biere_pomme", 
        ["DisplayName"] = "Biere à la pomme", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
	{
        ["Name"] = "biere_citron", 
        ["DisplayName"] = "Biere au citron", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },














		{
        ["Name"] = "ragout_cowboy", 
        ["DisplayName"] = "Ragout du Cowboy", 
        ["Animation"] = "bowl",
        ["PropName"] = "s_canbeans01x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
			{
        ["Name"] = "base_ragout", 
        ["DisplayName"] = "Base de ragout", 
        ["Animation"] = "bowl",
        ["PropName"] = "s_canbeans01x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
				{
        ["Name"] = "cocktail1", 
        ["DisplayName"] = "Cocktail pastèque", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
	{
        ["Name"] = "cocktail2", 
        ["DisplayName"] = "Cocktail bannane", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
	{
        ["Name"] = "sanglier_thym", 
        ["DisplayName"] = "Sanglier au thym", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "sanglier_thym", 
        ["DisplayName"] = "Sanglier au thym", 
        ["Animation"] = "shortbottle",
        ["PropName"] = "p_bottlebeer01a",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "poisson_thym", 
        ["DisplayName"] = "Perche au thym", 
        ["Animation"] = "bowl",
        ["PropName"] = "s_canbeans01x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
--
	{
        ["Name"] = "Bannana", 
        ["DisplayName"] = "Bannana", 
        ["Animation"] = "eat",
        ["PropName"] = "p_banana_day_01x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "Melone", 
        ["DisplayName"] = "Pastèque", 
        ["Animation"] = "eat",
        ["PropName"] = "p_watermelon03x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },


		{
        ["Name"] = "v_sechee", 
        ["DisplayName"] = "Viande séchée", 
        ["Animation"] = "eat",
        ["PropName"] = "p_salami_a_meat_b",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

			{
        ["Name"] = "baiesauv", 
        ["DisplayName"] = "Baie sauvages", 
        ["Animation"] = "bowl",
        ["PropName"] = "p_soupbowl01x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

				{
        ["Name"] = "b_mais", 
        ["DisplayName"] = "Bouillie de mais", 
        ["Animation"] = "bowl",
        ["PropName"] = "p_soupbowl01x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "sagamite", 
        ["DisplayName"] = "sagamite", 
        ["Animation"] = "bowl",
        ["PropName"] = "p_soupbowl01x",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },


	{
        ["Name"] = "pain_natif", 
        ["DisplayName"] = "pain natif", 
        ["Animation"] = "eat",
        ["PropName"] = "p_bread_14_ab_s",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 20,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0,
        --["OuterCoreHealth"] = 0,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "herbe_med", 
        ["DisplayName"] = "Herbes médicinales", 
        ["Animation"] = "eat",
        ["PropName"] = "p_bread_14_ab_s",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 0,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0100,
        ["OuterCoreHealth"] = 50,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "decoction_revigorante", 
        ["DisplayName"] = "Décoction revigorante", 
        ["Animation"] = "eat",
        ["PropName"] = "p_bread_14_ab_s",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 0,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0150,
        ["OuterCoreHealth"] = 50,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },


	{
        ["Name"] = "elixir_vivifiant", 
        ["DisplayName"] = "Elixir vivifiant", 
        ["Animation"] = "eat",
        ["PropName"] = "p_bread_14_ab_s",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 0,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0200,
        ["OuterCoreHealth"] = 100,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "p_soins_natif3", 
        ["DisplayName"] = "Premiers soins niv III", 
        ["Animation"] = "eat",
        ["PropName"] = "p_bread_14_ab_s",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 0,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0250,
        ["OuterCoreHealth"] = 100,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },

	{
        ["Name"] = "p_soins_natif3", 
        ["DisplayName"] = "Premiers soins niv III", 
        ["Animation"] = "eat",
        ["PropName"] = "p_bread_14_ab_s",
		["Remove"] = true,
        ["Metabolism"] = 115,
        ["Hunger"] = 0,
        ["Thirst"] = 0,
        ["InnerCoreStamina"] = 0,
        ["InnerCoreStaminaGold"] = 0.0,
        ["OuterCoreStaminaGold"] = 0.0,
        ["InnerCoreHealth"] = 0250,
        ["OuterCoreHealth"] = 100,
        ["InnerCoreHealthGold"] = 0.0,
        ["OuterCoreHealthGold"] = 0.0,
        ["HardAlcohol"] = false,
        ["SoftAlcohol"] = true,
        ["DrinkCount"] = 4,
        ["Effect"] = "PlayerDrunk01",
        ["EffectDuration"] = 90000,
    },
	
} 
